stages:
    - Revise
    - Prepare
    - Build
    - Combine
    - Clean
    - Staging

Revision Up:
  stage: Revise
  before_script:
  - whoami
  script:
    - num=0
    - num=`expr $VERSION_REVISION + 1`
    - echo $num
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/VERSION_REVISION"
    - 'docker run alpine/curl --insecure --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/VERSION_REVISION" --form "value=$num"'
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Version Up:
  stage: Build
  before_script:
    - update-ca-certificates
  script:
    - num=0
    - num=`expr $VERSION_REVISION + 1`
    - echo $num
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/VERSION_REVISION"
    - 'docker run alpine/curl --insecure --request PUT --header "PRIVATE-TOKEN: $API_TOKEN" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/variables/VERSION_REVISION" --form "value=$num"'
  only:
    - main


Build Api amd64:
  stage: Build
  needs:
    - Revision Up
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --push -f Dockerfile.Api -t $CI_REGISTRY/$CI_PROJECT_PATH/api-amd64:latest --build-arg ARCH=amd64/ .
    - docker build --push -f Dockerfile.Api -t $CI_REGISTRY/$CI_PROJECT_PATH/api-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --build-arg ARCH=amd64/ .
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Build Api arm64v8:
  stage: Build
  needs:
    - Revision Up
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --push -f Dockerfile.Api -t $CI_REGISTRY/$CI_PROJECT_PATH/api-arm64v8:latest --build-arg ARCH=arm64v8/ .
    - docker build --push -f Dockerfile.Api -t $CI_REGISTRY/$CI_PROJECT_PATH/api-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --build-arg ARCH=arm64v8/ .
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Build DbManager amd64:
  stage: Build
  needs:
    - Revision Up
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --push -f Dockerfile.DbManager -t $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-amd64:latest --build-arg ARCH=amd64/ .
    - docker build --push -f Dockerfile.DbManager -t $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --build-arg ARCH=amd64/ .
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Build DbManager arm64v8:
  stage: Build
  needs:
    - Revision Up
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --push -f Dockerfile.DbManager -t $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-arm64v8:latest --build-arg ARCH=arm64v8/ .
    - docker build --push -f Dockerfile.DbManager -t $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --build-arg ARCH=arm64v8/ .
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Build Service amd64:
  stage: Build
  needs:
    - Revision Up
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --push -f Dockerfile.Service -t $CI_REGISTRY/$CI_PROJECT_PATH/service-amd64:latest --build-arg ARCH=amd64/ .
    - docker build --push -f Dockerfile.Service -t $CI_REGISTRY/$CI_PROJECT_PATH/service-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --build-arg ARCH=amd64/ .
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Build Service arm64v8:
  stage: Build
  needs:
    - Revision Up
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --push -f Dockerfile.Service -t $CI_REGISTRY/$CI_PROJECT_PATH/service-arm64v8:latest --build-arg ARCH=arm64v8/ .
    - docker build --push -f Dockerfile.Service -t $CI_REGISTRY/$CI_PROJECT_PATH/service-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --build-arg ARCH=arm64v8/ .
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Combine Api:
  stage: Combine
  needs:
    - Build Api amd64
    - Build Api arm64v8
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/api:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-amd64:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-arm64v8:latest 
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/api:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-amd64:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-arm64v8:latest 
    - docker manifest push $CI_REGISTRY/$CI_PROJECT_PATH/api:latest
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/api:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION 
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/api:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/api-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION 
    - docker manifest push $CI_REGISTRY/$CI_PROJECT_PATH/api:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Combine DbManager:
  stage: Combine
  needs:
    - Build DbManager amd64
    - Build DbManager arm64v8
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-amd64:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-arm64v8:latest 
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-amd64:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-arm64v8:latest 
    - docker manifest push $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:latest
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION 
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION 
    - docker manifest push $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Combine Service:
  stage: Combine
  needs:
    - Build Service amd64
    - Build Service arm64v8
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/service:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-amd64:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-arm64v8:latest 
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/service:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-amd64:latest --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-arm64v8:latest 
    - docker manifest push $CI_REGISTRY/$CI_PROJECT_PATH/service:latest
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/service:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION 
    - docker manifest create $CI_REGISTRY/$CI_PROJECT_PATH/service:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-amd64:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION --amend $CI_REGISTRY/$CI_PROJECT_PATH/service-arm64v8:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION 
    - docker manifest push $CI_REGISTRY/$CI_PROJECT_PATH/service:$VERSION_MAJOR.$VERSION_MINOR.$VERSION_REVISION
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop