stages:
    - Test
    - Revise
    - Build
    - Release
    - Clean

include:
  - local: '/ci/gitversion-ci-cd-plugin-extension.gitlab-ci.yml' 

Test Service:
  stage: Test
  image: alpine:latest
  before_script:
    - apk add dotnet6-sdk
    - apk add weasyprint
  script:
    - dotnet test ./Prodromoi.Scheduler.Tests/Prodromoi.Scheduler.Tests.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

Test Api:
  stage: Test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet test ./Prodromoi.Api.Tests/Prodromoi.Api.Tests.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

Test Architecture:
  stage: Test
  image: mcr.microsoft.com/dotnet/sdk:6.0
  script:
    - dotnet test ./Prodromoi.Architecture.Tests/Prodromoi.Architecture.Tests.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
    reports:
      junit:
        - ./**/*test-result.xml

GitVersion:
  stage: Revise
  needs: 
    - Test Service
    - Test Api
    - Test Architecture
  extends: .gitversion_function
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop
    - main

Build API:
  stage: Build
  timeout: 30m
  needs:
    - GitVersion
  before_script:
    - echo "$GitVersion_SemVer"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --name multiarch.$CI_PIPELINE_IID.api --driver docker-container  --config ./ci/config.toml
    - docker buildx build --provenance false --builder multiarch.$CI_PIPELINE_IID.api -f Dockerfile.Api --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/api:latest .
    - docker buildx build --provenance false --builder multiarch.$CI_PIPELINE_IID.api -f Dockerfile.Api --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/api:$GitVersion_SemVer .
  after_script:
    - docker buildx rm multiarch.$CI_PIPELINE_IID.api 
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop
    - main

Build DbManager:
  stage: Build
  timeout: 30m
  needs:
    - GitVersion
  before_script:
    - echo "$GitVersion_SemVer"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --name multiarch.$CI_PIPELINE_IID.dbmanager --driver docker-container --config ./ci/config.toml
    - docker buildx build --provenance false --builder multiarch.$CI_PIPELINE_IID.dbmanager -f Dockerfile.DbManager --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:latest .
    - docker buildx build --provenance false --builder multiarch.$CI_PIPELINE_IID.dbmanager -f Dockerfile.DbManager --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/dbmanager:$GitVersion_SemVer .
  after_script:
    - docker buildx rm multiarch.$CI_PIPELINE_IID.dbmanager 
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop
    - main

Build Service:
  stage: Build
  timeout: 30m
  needs:
    - GitVersion
  before_script:
    - echo "$GitVersion_SemVer"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --name multiarch.$CI_PIPELINE_IID.service --driver docker-container  --config ./ci/config.toml
    - docker buildx build --provenance false --builder multiarch.$CI_PIPELINE_IID.service -f Dockerfile.Scheduler --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/service:latest .
    - docker buildx build --provenance false --builder multiarch.$CI_PIPELINE_IID.service -f Dockerfile.Scheduler --platform linux/amd64,linux/arm64 --push --cache-to type=local,dest=/var/image_cache,mode=max --cache-from type=local,src=/var/image_cache -t $CI_REGISTRY/$CI_PROJECT_PATH/service:$GitVersion_SemVer .
  after_script:
    - docker buildx rm multiarch.$CI_PIPELINE_IID.service 
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop
    - main

Pre-Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - GitVersion
    - Build API
    - Build DbManager
    - Build Service
  script:
    - echo "Pre-release $GitVersion_SemVer"
  release:
    name: 'Pre-Release $GitVersion_SemVer'
    tag_name: $GitVersion_SemVer
    description: |
      New version of Prodromoi backend services
      
      $GitVersion_InformationalVersion
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - develop

Release:
  stage: Release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - GitVersion
    - Build API
    - Build DbManager
    - Build Service
  script:
    - echo "Pre-release $GitVersion_SemVer"
  release:
    name: 'Release $GitVersion_SemVer'
    tag_name: $GitVersion_SemVer
    description: |
      New version of Prodromoi backend services

      $GitVersion_InformationalVersion
  only:
    - main

Sync Argo Develop:
  stage: Release
  image: bitnami/git:latest
  needs:
    - GitVersion
    - Build API
    - Build DbManager
    - Build Service
  before_script:
    - mkdir /git
    - cd /git
    - git -c http.sslVerify=false clone https://token:$ARGO_GIT_ACCESS@vulcan.samon.lata/scouts-tasmania/prodromoi/prodromoi-argocd.git
    - cd ./prodromoi-argocd/
    - git checkout develop
    - git -c http.sslVerify=false pull origin develop
  script:
    - sed -i "s|conreg.lanceolata.com.au/scouts-tasmania/prodromoi/prodromoi-api/dbmanager:.*|conreg.lanceolata.com.au/scouts-tasmania/prodromoi/prodromoi-api/dbmanager:$GitVersion_SemVer|g" ./app/api.yaml
    - sed -i "s|conreg.lanceolata.com.au/scouts-tasmania/prodromoi/prodromoi-api/api:.*|conreg.lanceolata.com.au/scouts-tasmania/prodromoi/prodromoi-api/api:$GitVersion_SemVer|g" ./app/api.yaml
    - git config --global user.name "CI/CD"
    - git config --global user.email "admin@lanceolata.com.au"
    - git add ./app/api.yaml
    - git commit -m "Upgrade to $GitVersion_SemVer for API & DB"
    - git -c http.sslVerify=false push origin develop
  only:
    - /^release.*$/
    - /^hotfix.*$/
    - main

Clean:
  stage: Clean
  timeout: 30m
  needs:
    - Build API
    - Build DbManager
    - Build Service
  script:
    docker system prune -a --force
  only:
    - develop
    - /^release.*$/
    - /^hotfix.*$/
    - main