FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env

WORKDIR /App

COPY . ./

RUN ["dotnet", "restore", "./Prodromoi.DbManager/Prodromoi.DbManager.csproj"]
RUN ["dotnet", "publish", "./Prodromoi.DbManager/Prodromoi.DbManager.csproj", "-c", "Release", "-o", "out"]


FROM mcr.microsoft.com/dotnet/runtime:6.0 as runtime

WORKDIR /App

COPY --from=build-env /App/out .
EXPOSE 80
ENTRYPOINT ["dotnet", "Prodromoi.DbManager.dll"]